permalink: /:year/:title

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - tools
  - go.mod
  - go.lock
  - Rakefile

s3: https://cdn.snorv.art
shopify: https://shop.jamesalistair.art

sass:
  sass_dir: _sass
  style: compressed
